// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx'
import * as $_app from './routes/_app.tsx'
import * as $_layout from './routes/_layout.tsx'
import * as $index from './routes/index.tsx'
import * as $wasm_path_ from './routes/wasm/[...path].ts'
import * as $Entry from './islands/Entry.tsx'
import * as $Header from './islands/Header.tsx'
import * as $WasmCanvas from './islands/WasmCanvas.tsx'
import type { Manifest } from '$fresh/server.ts'

const manifest = {
	routes: {
		'./routes/_404.tsx': $_404,
		'./routes/_app.tsx': $_app,
		'./routes/_layout.tsx': $_layout,
		'./routes/index.tsx': $index,
		'./routes/wasm/[...path].ts': $wasm_path_,
	},
	islands: {
		'./islands/Entry.tsx': $Entry,
		'./islands/Header.tsx': $Header,
		'./islands/WasmCanvas.tsx': $WasmCanvas,
	},
	baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
